name: Deploy to Hostinger VPS with Docker

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Deploy to Hostinger VPS
        uses: appleboy/ssh-action@master
        with:
          host: 149.100.156.79
          username: root
          key: ${{ secrets.SSH }}
          script: |
            # Update your Angular app on VPS
            cd /path/to/your/angular/app
            git pull origin master

            # Build Angular Frontend on VPS
            npm install
            npm run build -- --prod

            # Build Docker Image on VPS
            docker build -t your-docker-image-name .

            # Stop and remove existing container (if any)
            docker stop your-container-name || true
            docker rm your-container-name || true

            # Run Docker container on VPS
            docker run -d -p 80:80 -p 443:443 --name your-container-name your-docker-image-name
