name: Deploy to Hostinger VPS with Docker

on:
  pull_request:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Copy SSL Certificates from VPS to GitHub Pipeline
        uses: appleboy/ssh-action@master
        with:
          host: 149.100.156.79
          username: root
          key: ${{ secrets.SSH }}
          script: |
            mkdir -p /home/runner/work/ipwrc-frontend/ipwrc-frontend/ssl-certificates
            scp -r /etc/letsencrypt/live/plsvoldoende.nl/* /home/runner/work/ipwrc-frontend/ipwrc-frontend/ssl-certificates/

      - name: Check SSL Certificates Directory
        run: |
          echo "SSL Certificates Directory Path: $(pwd)/ssl-certificates"
          ls /home/runner/work/ipwrc-frontend/ipwrc-frontend/ssl-certificates

      - name: Build Angular Frontend
        run: |
          npm install
          npm run build -- --prod
          docker build -t ${{ secrets.DOCKER_USERNAME }}/ipwrcfrontend .

      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASS }}

      - name: Build Docker Image with SSL Certificates
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/ipwrcfrontend:with-ssl .
          docker push ${{ secrets.DOCKER_USERNAME }}/ipwrcfrontend:with-ssl

      - name: Deploy to Hostinger VPS
        uses: appleboy/ssh-action@master
        with:
          host: 149.100.156.79
          username: root
          key: ${{ secrets.SSH }}
          script: |
            docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASS }}
            docker pull ${{ secrets.DOCKER_USERNAME }}/ipwrcfrontend:with-ssl
            docker stop ipwrcfrontend || true
            docker rm ipwrcfrontend || true
            docker run -d -p 80:80 -p 443:443 --name ipwrcfrontend ${{ secrets.DOCKER_USERNAME }}/ipwrcfrontend:with-ssl
