name: Deploy to Hostinger VPS with Docker

on:
  pull_request:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Copy SSL Certificates from VPS to GitHub Pipeline
        uses: appleboy/ssh-action@master
        with:
          host: 149.100.156.79
          username: root
          key: ${{ secrets.SSH }}
          script: |
            - name: Copy SSL Certificates from VPS to GitHub Actions runner
              run: |
                # Check the SSL certificates directory on VPS
                ls /etc/letsencrypt/live/plsvoldoende.nl

                # Create a tarball of the SSL certificates on VPS
                tar -czf /tmp/ssl-certificates.tar.gz -C /etc/letsencrypt/live/plsvoldoende.nl .

                # Copy the tarball from VPS to GitHub Actions runner
                scp root@149.100.156.79:/tmp/ssl-certificates.tar.gz /home/runner/work/ipwrc-frontend/ipwrc-frontend/

                # Extract SSL Certificates on GitHub Actions runner
                tar -zxvf /home/runner/work/ipwrc-frontend/ipwrc-frontend/ssl-certificates.tar.gz -C /home/runner/work/ipwrc-frontend/ipwrc-frontend/

      - name: Build Angular Frontend
        run: |
          npm install
          npm run build -- --prod
          docker build -t ${{ secrets.DOCKER_USERNAME }}/ipwrcfrontend .

      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASS }}

      - name: Build Docker Image with SSL Certificates
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/ipwrcfrontend:with-ssl .
          docker push ${{ secrets.DOCKER_USERNAME }}/ipwrcfrontend:with-ssl

      - name: Deploy to Hostinger VPS
        uses: appleboy/ssh-action@master
        with:
          host: 149.100.156.79
          username: root
          key: ${{ secrets.SSH }}
          script: |
            docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASS }}
            docker pull ${{ secrets.DOCKER_USERNAME }}/ipwrcfrontend:with-ssl
            docker stop ipwrcfrontend || true
            docker rm ipwrcfrontend || true
            docker run -d -p 80:80 -p 443:443 --name ipwrcfrontend ${{ secrets.DOCKER_USERNAME }}/ipwrcfrontend:with-ssl
