name: Deploy to Hostinger VPS with Docker

on:
  pull_request:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Build Angular Frontend
        run: |
          npm install
          npm run build -- --prod
          docker build -t ${{ secrets.DOCKER_USERNAME }}/ipwrcfrontend .

      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASS }}

      - name: Build Docker Image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/ipwrcfrontend:latest .
          docker push ${{ secrets.DOCKER_USERNAME }}/ipwrcfrontend:latest

      - name: Deploy to Hostinger VPS
        uses: appleboy/ssh-action@master
        with:
          host: 149.100.156.79
          username: root
          key: ${{ secrets.SSH }}
          script: |
            docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASS }}
            docker pull ${{ secrets.DOCKER_USERNAME }}/ipwrcfrontend:latest
            docker stop ipwrcfrontend || true
            docker rm ipwrcfrontend || true
            docker run -d -p 80:80 -p 443:443 \
              -v mycerts:/certs \
              -v /etc/letsencrypt/live/plsvoldoende.nl/fullchain.pem:/certs/fullchain.pem \
              -v /etc/letsencrypt/live/plsvoldoende.nl/privkey.pem:/certs/privkey.pem \
              --name ipwrcfrontend ${{ secrets.DOCKER_USERNAME }}/ipwrcfrontend:latest




